Numpy Revision

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [7]:
arr = np.array(mylist)
arr

array([1, 2, 3])

In [8]:
type(arr)

numpy.ndarray

In [10]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
mymatrix = np.array(mylist)
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
mymatrix.shape

(3, 3)

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [22]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [23]:
#lineraly spaced
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
len(np.linspace(0,10,20))

20

In [25]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(1)

array([0.99770292])

In [27]:
np.random.rand(5,5)

array([[0.19282847, 0.98965929, 0.67732967, 0.10407178, 0.47975352],
       [0.77397445, 0.10627573, 0.03314177, 0.20832649, 0.11579812],
       [0.05951972, 0.65949679, 0.69265401, 0.30069996, 0.05612035],
       [0.02213496, 0.19795131, 0.19902969, 0.3460834 , 0.15275411],
       [0.246658  , 0.51788285, 0.78559387, 0.26494386, 0.98537417]])

In [28]:
np.random.randn(4,5)

array([[-0.25241627,  0.24618245,  0.19965513,  0.19468826,  0.07811884],
       [-0.02722651,  1.4694417 , -0.08413784,  0.16525954,  0.12714824],
       [ 0.47696278,  0.25010496,  1.32934807,  1.33128962,  0.96753683],
       [-0.13871278, -0.42080458,  0.29105861, -0.1123531 ,  0.57700289]])

In [30]:
np.random.randint(1,100,10)

array([44, 71, 56, 52, 88, 68, 78, 87, 37, 79])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr.max()

39

In [39]:
ranarr.min()

2

In [40]:
# returns index of max number
ranarr.argmax()

7

In [41]:
# returns index of min number
ranarr.argmin()

9

In [42]:
ranarr.dtype

dtype('int32')

In [43]:
# Indexing and Selection
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[8]

8

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
# Broadcasting
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [50]:
arr / 2 

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
new_arr = arr +100
new_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [53]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [55]:
# Slicing
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [58]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_copy[:] = 1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
# Indexing on 2 Dimensional array aka Matrix
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d.shape

(3, 3)

In [65]:
arr_2d[1]

array([20, 25, 30])

In [66]:
arr_2d[1][1]

25

In [67]:
arr_2d[1,1]

25

In [68]:
arr_2d[2,2]

45

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
# Conditional Selection, V.impt
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [73]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [74]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
# similar to above but in one step
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
arr[arr == 2]

array([2])

In [80]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

In [81]:
# Numpy Operations
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [83]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [84]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [85]:
(arr + 2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [86]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
1/arr

C:\Users\manor\anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [88]:
arr/arr

C:\Users\manor\anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [89]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [90]:
np.log(arr)

C:\Users\manor\anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [91]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [92]:
arr.sum()

45

In [93]:
arr.mean()

4.5

In [94]:
arr.std()

2.8722813232690143

In [95]:
arr.max()

9

In [96]:
arr.min()

0

In [97]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
arr_2d.shape

(3, 4)

In [99]:
arr_2d.sum()

78

In [102]:
# Sum across the rows
arr_2d.sum(axis = 0)
# Returns the sum of the values in columns

array([15, 18, 21, 24])

In [103]:
# Sum across the columns
arr_2d.sum(axis = 1)
# Returns the sum of the values in rows

array([10, 26, 42])

                            Pandas
                            
                            - Series and DataFrames
                            
                            - Missing Data
                            
                            - GroupBy
                            
                            - Operations
                            
                            - Data I/O (Input and Output)
                            
                            - Exercises

In [ ]:
# Series

